version: '3'

services:
  standarddot_test:
    build:
      context: .
      dockerfile: src/Test.Dockerfile
      args:
        NUGET_PACKAGE_SOURCE: "https://api.nuget.org/v3/index.json"
        # you may want to skip this install if you aren't running sonarqube
        INSTALL_SONAR_SCANNER: "true"
        # these have good defaults
        # SONAR_SCANNER_HOME:
        # SONAR_SCANNER_OPTS:
        # SONAR_SCANNER_VERSION:
    volumes:
      - ./:/app
    depends_on:
      - standarddot_redis
    environment:
      - SONAR_LOGIN
      - SONAR_HOST
      - SONAR_PROJECTKEY
      - SONAR_ORGANIZATION

  standarddot_redis:
    image: redis:5-alpine