version: '3'

services:
  standarddot_update_packages:
    build:
      context: .
      dockerfile: src/UpdatePackages.Dockerfile
      args:
        NUGET_PACKAGE_SOURCE: "https://api.nuget.org/v3/index.json"
    volumes:
      - ./:/app
    environment:
      - GIT_BRANCH_NAME
      - GIT_BRANCH_TARGET
      - SONAR_PROJECTKEY
      - NUGET_API_KEY
      - NUGET_PUSH_SOURCE=https://www.nuget.org/api/v2/package