version: '3'

services:
  terminal:
    build:
      context: .
      dockerfile: Shell.Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - redis
    stdin_open: true
    tty: true
  redis:
    image: redis:alpine